services:
  loadtest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 19091:8080
    volumes:
      - ./load-test:/app
  prometheus:
    image: prom/prometheus
    ports:
      - 19090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml